language: python
env:
  global:
    CODECOV_TOKEN: d2f53ce3-9895-412b-bcbc-39b569d78198
python:
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install -r requirements.txt
script:
  - pytest
after_success:
  - codecov
